name: MessagealarmCI

env:
  REG_HOST: docker.webtest.51beige.com
  IMAGE_NAME: crm-warning-backend

on:
  push:
    tags:
      - "v*"

jobs:

  prometheusAlert:

    name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: messagealarm

    strategy:
      matrix:
        go_version: [ 1.17 ]
        os: [ ubuntu-latest ]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run go modules tidy
        run: |
          go mod tidy

      - name: Docker tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${REG_HOST}

      - name: Build image
        env:
          GOPROXY: https://goproxy.io,direct
        run: scripts/run_build.sh ${REG_HOST} ${{ steps.vars.outputs.tag }}